### ISSUE TITLE
关于外接显示器的曲线救国解决方案

### ISSUE THREAD

**Issue by kirainmoe** [kirainmoe/hasee-z7-kp7gz-macos#10]
因为下面的内容有广告嫌疑，所以不将此方法加入到 README 中。

这台笔记本用的模具将 HDMI 和两个 miniDP 接口都接在了独立显卡上，而 macOS 下独立显卡又无法驱动，这相当于封死了在 macOS 下外接显示器的可能——吗？人类的智慧是无穷的，经过论坛和群里的朋友测试，发现只需要购买特定的 USB3.0/Type-C 转 HDMI 转换器，就可以在 macOS 下外接显示器。

当然，“特定的”转换器，意味着并不是所有的 USB/Type-C 转 HDMI 都可以外接拓展屏。你需要购买那些内置了转换芯片、在 macOS 下免驱的转换器才可以，原理是这样的转换器相当于外置了一个“显卡”来拓展信号。使用这种外接转换器可以完美解决因为显卡无法驱动而无法外接显示器的问题，但是它同样存在缺点，例如：可能会有几十毫秒的延迟、价格较贵等。因此，如果你特别需要外接显示器，目前唯一的解决方案就是购买转换器。

需要注意的是，市面上大部分 USB/Type-C 转 HDMI 转换器都是不带符合条件的芯片的（请注意，并不是带“芯片”就可以），在你购买之前请务必从商品详情确认其带有独立的芯片、支持 macOS. 如果你不知道什么样的产品符合上述描述，这里有一个可选的产品：[绿联usb3.0转hdmi外置显卡转换线适用苹果笔记本连高清显示器DVI惠普电脑接电视投影仪MakeBook air/pro](https://detail.tmall.com/item.htm?id=520810798226&price=268&sourceType=item&sourceType=item&suid=c0e06e02-eca7-4949-859f-50f704ed7858&ut_sk=1.W1FxXEBOiAIDAMpQQBcKMU1E_21646297_1554565312690.TaoPassword-QQ.1&un=815ec26d54b1218f4b68d5f77a161062&share_crt_v=1&sp_tk=77%20la2ZLWWJ6cDc0WnLvv6U=&cpp=1&shareurl=true&spm=a313p.22.29d.1023943297917&short_name=h.eZ3KZB6&app=chrome&sku_properties=122216547:493262823)

请注意，上述列出的只是一个在论坛有成功案例、符合条件的产品。在此声明，我与该产品的卖家没有任何利益相关；所以遇到什么产品相关的问题跟我也没有关系。如果有的话，你也可以选择其它带转换芯片、macOS 下可用的产品，并与我们分享。

以上。

**Comment by kirainmoe** [comment]
再次提醒：我个人没有外接显示器的需求，也没有外接测试的条件，所以我不对任何产品的可用性负责。上面的产品价格很贵，但他是群里有人测试过、真正可用的，我才在这里推荐；如果有需要可以闲鱼找找。其它产品可能有相同的效果并且价格更低，但我并不保证其它产品的可用性。购买其他产品时也请不要盲目相信客服，建议购买运费险以便在不能用的时候退货。

**Comment by kirainmoe** [comment]
添加两个群中网友测试可用的产品：

[j5create JUA254 USB3.0转HDMI外置显卡电视转换器投影仪转接头](https://item.jd.com/30670138779.html)，最高支持 2048x1152 分辨率 （建议使用 1080p）

[j5create JUA365 USB3.0转HDMI线双独立外置显卡转换器 4K高清转接头扩展坞](https://item.jd.com/30674043810.html)，最高支持 4K 30Hz 与 2K 60Hz

另外，理论上支持 DisplayLink 协议的产品也是可以的，只是需要自己下载并安装 DisplayLink 的驱动。

**Comment by insmoin** [comment]
j5create JUA365 USB3.0 支持2k 60hz

**Comment by glitterlip** [comment]
jua254 1080p 可以用,但是会拖影

**Comment by WangChenPeng** [comment]
j5create JUA254 USB3.0使用正常 终于能分屏了 泪目

**Comment by WangChenPeng** [comment]
各位买的时候 一定要注意分辨率的问题...我没看...结果买的这款支持不了带鱼屏 尴尬

**Comment by isnowify** [comment]
Lenovo AN9017D1 正常使用，咸鱼购入，是个50元以下廉价接入副屏的不错选择。

**Comment by bkingalex** [comment]
> Lenovo AN9017D1 正常使用，咸鱼购入，是个50元以下廉价接入副屏的不错选择。

能发个具体型号吗，搜索：Lenovo AN9017D1 ，什么都搜索不到

**Comment by AmazingPP** [comment]
j5create  JUA214 使用正常，主要是便宜，只要59元。驱动一定要按README里的步骤装好，要给屏幕录制权限。

[j5create JUA214 USB3.0转VGA线转换器](https://item.jd.com/30668797010.html)

[JUA214 / JUA254驱动](http://download.j5create.com/driver/USB_Display_Adapters_Mac_Driver/download.php)

**Comment by WPNEAL** [comment]
> j5create JUA214 使用正常，主要是便宜，只要59元。驱动一定要按README里的步骤装好，要给屏幕录制权限。
> 
> [j5create JUA214 USB3.0转VGA线转换器](https://item.jd.com/30668797010.html)
> 
> [JUA214 / JUA254驱动](http://download.j5create.com/driver/USB_Display_Adapters_Mac_Driver/download.php)

公司的显示器是vga接口的，所以买的这款，可以使用，感谢

**Comment by kiraraty** [comment]
> Lenovo AN9017D1 正常使用，咸鱼购入，是个50元以下廉价接入副屏的不错选择。

搜索不到啊

**Comment by rodgomesc** [comment]
[dell d6000](https://www.dell.com/pt-br/shop/dock-station-universal-da-dell-d6000/apd/452-bcqi/acess%C3%B3rios-para-computador?utm_campaign=google-shopping&utm_source=google-shopping&gacd=9694601-15002-5761040-276881644-0&dgc=ST&cid=71700000069466860&gclid=CjwKCAjwxuuCBhATEiwAIIIz0fv8umVS0y47AEcW7S0zKt6KhkQALifXjmFVXQwmDCbEFi_cNF8y8RoCGTIQAvD_BwE&gclsrc=aw.ds)
 
 - working with 2 extra monitors, but support 3
 - connected on usb-c or other usb 2.0/3.0
 - uses displaylink protocol
 
![image.png](https://i.loli.net/2021/03/24/mexNV12vOtCiLjd.png)

**Comment by marcustut** [comment]
![image](https://user-images.githubusercontent.com/59773847/119678431-14d53b80-be72-11eb-9bea-e0c27a1f155d.png)

在寻找着该买哪一款 转换器 的时候在GitHub主页有看到以上这个信息，那我能够使用type-c接口去输出视频吗？

我需要有两个HDMI的输出口，所以暂时的选择是 JUA365 和 JCD381 它们俩主要的区别在于 JUA365 是 USB3.0 Type-A 而 JCD381是 USB3.1 Type-C

[j5create JCD381 USB Type-C转双HDMI](https://info.j5create.com/products/jcd381)

PS：我使用的是Tongfang GK5CP5V

**Comment by kirainmoe** [comment]
Type-C 不支持视频输出指的是不支持通过 Type-C 连接核显。转换器走的均为 USB 3.1 协议，可以正常使用。

**Comment by marcustut** [comment]
> Type-C 不支持视频输出指的是不支持通过 Type-C 连接核显。转换器走的均为 USB 3.1 协议，可以正常使用。

好，谢谢你那么神速的回复！

**Comment by kiraraty** [comment]
我的是蓝天模 具  有一个minidp是连在核显上的（在win下测试）请问是需要定制dp接口才能在mac下面使用吗  有教程吗  感谢大佬

**Comment by kirainmoe** [comment]
[利用Hackintool打开第8代核显HDMI/DVI输出的正确姿势](https://blog.daliansky.net/Tutorial-Using-Hackintool-to-open-the-correct-pose-of-the-8th-generation-core-display-HDMI-or-DVI-output.html)

另参阅 [英特尔® 核芯显卡 常见问答](https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.IntelHD.cn.md)

**Comment by marcustut** [comment]
[j5create JCD381 USB Type-C转双HDMI](https://info.j5create.com/products/jcd381)

![image](https://user-images.githubusercontent.com/59773847/120448367-16e15200-c3be-11eb-8212-918dacddc41f.png)

正常使用 2560x1440 60fps 通过 Type-C

**Comment by marcustut** [comment]
[j5create JCD381 USB Type-C转双HDMI](https://info.j5create.com/products/jcd381)

![image](https://user-images.githubusercontent.com/59773847/120448367-16e15200-c3be-11eb-8212-918dacddc41f.png)

正常使用 2560x1440 60fps 通过 Type-C

**Comment by HhjWxx** [comment]
想要购买 dell d6000，但是不知道机械革命 Z2 能否通过这个扩展坞实现 4K 60HZ

**Comment by 1103409364** [comment]
> 想要购买 dell d6000，但是不知道机械革命 Z2 能否通过这个扩展坞实现 4K 60HZ

DisplayLink 方案接 4k 显示器延迟高到你不想用，编辑文本都难受的一批

**Comment by HhjWxx** [comment]
最终还是购买了，不过使用起来还是能够接受的

**Comment by kirklin** [comment]
求助大佬们，34寸带鱼屏，伪4K，100HZ用哪个转接线可以完美支持。

**Comment by zhoujia456888** [comment]
有没有平价一点能接2K显示器的方案？JCD381都500多块钱了，穷人负担不起呀。

**Comment by zhoujia456888** [comment]
最终迫于无奈在咸鱼买了一个350块钱的扩展，型号不太清楚，品牌叫itec,卖家说支持displaylink。实测需要下载displayLink[驱动](https://www.synaptics.com/products/displaylink-graphics/downloads)。
实物长这个样子
![image](https://user-images.githubusercontent.com/7905253/156130026-e08fbb58-0eeb-452f-8b1a-a28b42379e7c.png)
![image](https://user-images.githubusercontent.com/7905253/156130063-1abc8acc-dae4-4f55-b0e8-cc1c1956c87c.png)

**Comment by HhjWxx** [comment]
我买的  DELL D6000P 也就 400

**Comment by xinjiajuan** [comment]
2022年考古
我电脑是z7-ct5na，在win下面我用带hdmi接口的拓展坞（这种应该没有像上面介绍的usb/type-c转hdmi转接器的那种芯片）连接type-c接口，hdmi连接屏幕，屏幕识别为连接到英伟达独立显卡，内屏是核显直连。
我想问如果买个上面介绍过的那种type-c转接器，他还会被直接识别为独立显卡直连吗？我担心这个type-c不能连核显。

**Comment by xinjiajuan** [comment]
> 2022年考古 我电脑是z7-ct5na，在win下面我用带hdmi接口的拓展坞（这种应该没有像上面介绍的usb/type-c转hdmi转接器的那种芯片）连接type-c接口，hdmi连接屏幕，屏幕识别为连接到英伟达独立显卡，内屏是核显直连。 我想问如果买个上面介绍过的那种type-c转接器，他还会被直接识别为独立显卡直连吗？我担心这个type-c不能连核显。

我考虑的是type-c带宽会大很多

**Comment by kirklin** [comment]
> 2022年考古 我电脑是z7-ct5na，在win下面我用带hdmi接口的拓展坞（这种应该没有像上面介绍的usb/type-c转hdmi转接器的那种芯片）连接type-c接口，hdmi连接屏幕，屏幕识别为连接到英伟达独立显卡，内屏是核显直连。 我想问如果买个上面介绍过的那种type-c转接器，他还会被直接识别为独立显卡直连吗？我担心这个type-c不能连核显。

Mac下，应该识别不了，得要那种带芯片的，或者displaylink

**Comment by xinjiajuan** [comment]
> > 2022年考古 我电脑是z7-ct5na，在win下面我用带hdmi接口的拓展坞（这种应该没有像上面介绍的usb/type-c转hdmi转接器的那种芯片）连接type-c接口，hdmi连接屏幕，屏幕识别为连接到英伟达独立显卡，内屏是核显直连。 我想问如果买个上面介绍过的那种type-c转接器，他还会被直接识别为独立显卡直连吗？我担心这个type-c不能连核显。
> 
> Mac下，应该识别不了，得要那种带芯片的，或者displaylink

有推荐吗，更便宜点的，支持2k

**Comment by limit81995** [comment]
> 最终迫于无奈在咸鱼买了一个350块钱的扩展，型号不太清楚，品牌叫itec,卖家说支持displaylink。实测需要下载displayLink[驱动](https://www.synaptics.com/products/displaylink-graphics/downloads)。 实物长这个样子 ![image](https://user-images.githubusercontent.com/7905253/156130026-e08fbb58-0eeb-452f-8b1a-a28b42379e7c.png) ![image](https://user-images.githubusercontent.com/7905253/156130063-1abc8acc-dae4-4f55-b0e8-cc1c1956c87c.png)

你这用的怎么样，有拖影和延迟吗

**Comment by zhoujia456888** [comment]
> 
我用着感觉还行，我显示器是安美特的24寸、2K、60HZ，用着基本没有延迟和拖影，就是偶尔会卡顿一下（也有可能是系统卡顿），

**Comment by limit81995** [comment]
> > 
> 
> 我用着感觉还行，我显示器是安美特的24寸、2K、60HZ，用着基本没有延迟和拖影，就是偶尔会卡顿一下（也有可能是系统卡顿），

可以拍一下背后 标签吗，我看一下型号也去搞一个

**Comment by zhoujia456888** [comment]
> > > 
> > 
> > 
> > 我用着感觉还行，我显示器是安美特的24寸、2K、60HZ，用着基本没有延迟和拖影，就是偶尔会卡顿一下（也有可能是系统卡顿），
> 
> 可以拍一下背后 标签吗，我看一下型号也去搞一个

![image](https://user-images.githubusercontent.com/7905253/182341045-90ce0b7c-9954-4d7c-aece-929d65015d3a.png)

**Comment by xinjiajuan** [comment]
我现在有个拓展坞闲置了，有需要的朋友可以看看
【闲鱼】https://m.tb.cn/h.UXsBTWO?tk=IqWY2CWAsq6 CZ0001 「我在闲鱼发布了【plugable UD-6850H】」
点击链接直接打开

**Comment by enkialtria** [comment]
带鱼屏能用吗
