### ISSUE TITLE
耀7000 声卡仿冒100系 解决启动无声 建议尝试

### ISSUE THREAD

**Issue by jinmu333** [kirainmoe/hasee-z7-kp7gz-macos#12]
同模具 的耀7000 声卡同样偶尔启动无声 多次重启可以解决
Hackintool 仿冒100系 加下面两个驱动已解决
![image](https://user-images.githubusercontent.com/32295532/57140884-6faf1c80-6deb-11e9-9bc1-4d44465a7814.png)

![image](https://user-images.githubusercontent.com/32295532/57140840-5017f400-6deb-11e9-83d0-42be82e0ac65.png)

**Comment by kirainmoe** [comment]
嗯，我也是昨天爬帖刚发现的，加那两个驱动就解决了。
