### ISSUE TITLE
Clover 界面的问题

### ISSUE THREAD

**Issue by pexcn** [kirainmoe/hasee-z7-kp7gz-macos#14]
![photo_2019-05-05_17-26-29](https://user-images.githubusercontent.com/4590439/57191700-fe8e7700-6f5a-11e9-945c-f3d0cf542c10.jpg)

如上图所示，请问：
1. "Boot Windows from EFI" 能自定义为 "Windows" 吗？
2. 最后一个启动的选项是 "Boot Recovery.....", 进入了卡死了，似乎不能启动，能否去掉？

**Comment by kirainmoe** [comment]
1. 不可以
2. 可以在 Clover Configurator / GUI 的 Hide Volume 中添加 Recovery 隐藏项。

**Comment by pexcn** [comment]
嗯，再问下，Recovery 这个启动项有什么用的？为什么不能进去呢？

**Comment by kirainmoe** [comment]
Recovery 是 macOS 的恢复模式，系统无法进入时可以在 Recovery 中使用磁盘工具，终端，时间机器等。我这里本地测试可以进去。

**Comment by pexcn** [comment]
我应该要做一些什么操作才能进入 Recovery 模式？目前只是安装了系统，尝试进入却不能进入。

**Comment by kirainmoe** [comment]
安装完默认就可以进入，需要等3分钟左右的时间。如果无法进入请贴 -v log.

**Comment by pexcn** [comment]
好的，我有空再尝试下

**Comment by pexcn** [comment]
![6F468C40-AE5D-4D3A-8D4D-E08907B1CC82](https://user-images.githubusercontent.com/4590439/57458036-3cfd9c00-72a3-11e9-9444-fb2c79dddfff.jpeg)

加上 -v 进入 Recovery 模式，一直卡在这里了

**Comment by kirainmoe** [comment]
尝试勾选 nv_disable=1 引导参数。如果还是不行尝试 -liluoff 参数。如果都不行，原因可能是配置文件不完整或者安装镜像的问题。

事实上这个 Recovery 正常情况下并没有什么用。

**Comment by pexcn** [comment]
镜像我用的是 https://blog.daliansky.net/macOS-Mojave-10.14.4-18E226-official-version-with-Clover-4903-original-image.html 这个，请问大佬你是用哪个镜像的？

**Comment by kirainmoe** [comment]
也是这个镜像。

**Comment by pexcn** [comment]
启动参数加了 `nv_disable=1`，终于可以进入了。
