### ISSUE TITLE
请问一下z7m-kp7gt可以安装吗

### ISSUE THREAD

**Issue by NatsumeXavier** [kirainmoe/hasee-z7-kp7gz-macos#16]
请问一下z7m-kp7gt可以安装吗

**Comment by kirainmoe** [comment]
z7m-kp7gt 可以安装，但不可以使用 kp7gz 系列的 EFI 安装，前者是 7 代酷睿平台，后者是酷睿 8 代平台。

建议同方模具的 kp7gt 和 kp7d2 安装 10.13.6 或 10.14.3 以下版本。
