### ISSUE TITLE
安装完 macOS 之后，在 EFI 分区多了个 "EFI/APPLE" 文件夹

### ISSUE THREAD

**Issue by pexcn** [kirainmoe/hasee-z7-kp7gz-macos#17]
![屏幕截图(8)](https://user-images.githubusercontent.com/4590439/57458495-0b390500-72a4-11e9-87d5-c7fef8414c6a.png)

`EFI/APPLE` 这个文件夹可以删除吗？有什么作用？

**Comment by kirainmoe** [comment]
没有什么用。可以删除，但是在系统内检查更新时还是会自动创建。

**Comment by pexcn** [comment]
好的 :)
