### ISSUE TITLE
开启 HiDPI 之后重启不能保存亮度

### ISSUE THREAD

**Issue by pexcn** [kirainmoe/hasee-z7-kp7gz-macos#18]
使用这里的脚本 https://github.com/xzhih/one-key-hidpi 开启 HiDPI，手动选择 1600x900 1440x810 1280x720 这三档分辨率，每次重启 macOS 之后亮度总是最高的。

顺便问下想开启 HiDPI 的最佳姿势是什么？

**Comment by kirainmoe** [comment]
建议检查 SSDT-ALS0.aml 是否存在并加载，以及 NVRAM 模拟是否正常工作。  
另外，使用第三方程序导致的配置文件工作不正常不在我的责任范围之内。  
HiDPI 原本就是不推荐启用的操作。

**Comment by pexcn** [comment]
还有个问题，为什么不要注入EDID？ https://kirainmoe.com/blog/post/guide-on-hasee-z7-kp7gz-hackintosh-macos-mojave/

在我这里用这个脚本注入了 EDID 之后，睡眠后醒来花屏的问题没有了，但是不能保存之前设置好的分辨率

**Comment by kirainmoe** [comment]
不需要，不是不要。你要注入也可以，我只是说“开启 HiDPI 只需要脚本，不需要修改注入 EDID 等”。注入EDID可以解决八苹果问题等。

**Comment by pexcn** [comment]
> 建议检查 SSDT-ALS0.aml 是否存在并加载，以及 NVRAM 模拟是否正常工作。
> 另外，使用第三方程序导致的配置文件工作不正常不在我的责任范围之内。
> HiDPI 原本就是不推荐启用的操作。

请问以上的东西用哪些工具检查？

**Comment by kirainmoe** [comment]
> > 建议检查 SSDT-ALS0.aml 是否存在并加载，以及 NVRAM 模拟是否正常工作。
> > 另外，使用第三方程序导致的配置文件工作不正常不在我的责任范围之内。
> > HiDPI 原本就是不推荐启用的操作。
> 
> 请问以上的东西用哪些工具检查？

肉眼检查。SSDT-ALS0.aml 在 EFI文件夹的 ACPI/patched 下；至于 NVRAM 可以自己 Google 搜索 NVRAM emulate.

**Comment by pexcn** [comment]
嗯嗯，好
