### ISSUE TITLE
我的是z7sp5d1，CPU是I5 6300HQ求教程

### ISSUE THREAD

**Issue by 532609499** [kirainmoe/hasee-z7-kp7gz-macos#19]
蓝天的磨具，显卡一样，CPU不同能装么

**Comment by kirainmoe** [comment]
不可以。6代和8代天差地别，模具也天差地别，反倒是显卡一样没有什么卵用，因为独显是屏蔽的。

**Comment by limbodiyu** [comment]
z7sp5d1 mac efi  可以来https://github.com/moonheart/Hackintosh-P65xRP6-Z7-SP5D1  这个下
