### ISSUE TITLE
USBPorts.kext使用后鼠标无法使用，只能用usbInjectAll.kext驱动

### ISSUE THREAD

**Issue by jkdep001** [kirainmoe/hasee-z7-kp7gz-macos#2]
USBPorts.kext使用后鼠标无法使用，只能用usbInjectAll.kext驱动

**Comment by kirainmoe** [comment]
安装到 /L/E 或 /S/L/E 后重建缓存即可，这次重装也发现了这个问题，忘记补充说明了。

**Comment by jkdep001** [comment]
就是使用 Kext Utility  直接 允许吗？非常感谢！！！

**Comment by kirainmoe** [comment]
是的。

**Comment by jkdep001** [comment]
能不能帮忙看一下使用usbport.kext 导致usb 设备全部不能加载。下面的 查询信息，万分感谢
`Index Refs Address            Size       Wired      Name (Version) UUID <Linked Against>
    1   95 0xffffff7f80c42000 0x9e50     0x9e50     com.apple.kpi.bsd (18.2.0) 6227C138-5CBA-45D7-9AE0-6E9DB11374B0
    2   13 0xffffff7f80f84000 0x3900     0x3900     com.apple.kpi.dsep (18.2.0) DF170CBB-E68F-4A76-AD41-EF16740CF2EE
    3  132 0xffffff7f80c20000 0x21be0    0x21be0    com.apple.kpi.iokit (18.2.0) BBAD07CC-E25A-47A2-9F4F-918F02DFF8C5
    4    0 0xffffff7f80f8b000 0x34b0     0x34b0     com.apple.kpi.kasan (18.2.0) A96ED517-EE7C-45EB-B542-AA5C8561079C
    5  138 0xffffff7f80c00000 0xd7b0     0xd7b0     com.apple.kpi.libkern (18.2.0) CA65EA53-4484-4961-8113-F5ECA0ED75AE
    6  121 0xffffff7f80c0e000 0x3f60     0x3f60     com.apple.kpi.mach (18.2.0) AEE523DE-E508-478E-BAD2-32B5F7F2A6DC
    7   74 0xffffff7f80c12000 0xd480     0xd480     com.apple.kpi.private (18.2.0) 2346E370-ECC7-4391-87C7-0A1E389D913D
    8   88 0xffffff7f80c8f000 0x5ed0     0x5ed0     com.apple.kpi.unsupported (18.2.0) DAC9D4F7-D777-4F09-9A73-EFA7954948F7
    9    8 0xffffff7f80f8f000 0xb5000    0xb5000    com.apple.kec.corecrypto (1.0) 46F3B625-86D1-3761-9603-34835A98AA49 <8 7 6 5 3 1>
   10    0 0xffffff7f8114a000 0xa000     0xa000     com.apple.kec.pthread (1) F4714573-8F64-35BD-9C41-5D4BDCBFAD1C <8 7 6 5 3 1>
   11    2 0xffffff7f8118b000 0x10000    0x10000    com.apple.kec.Libm (1) 2DF6EF8D-C4B1-3754-883E-192ABD2743DB <5>
   12   28 0xffffff7f8119b000 0x9000     0x9000     com.apple.iokit.IOACPIFamily (1.4) 67079254-1B34-31D2-8C7B-B138E26BFDD8 <8 7 5 3>
   13   34 0xffffff7f80c95000 0x35000    0x35000    com.apple.iokit.IOPCIFamily (2.9) 5C9A453F-559B-3683-9E81-D288D13A33CE <8 7 6 5 3>
   14    9 0xffffff7f811a4000 0x1e000    0x1e000    com.apple.driver.AppleSMC (3.1.9) 4523E39C-6A5A-3352-BE3B-2B3BD9B70251 <13 12 8 7 6 5 3 1>
   15    2 0xffffff7f83009000 0x9c000    0x9c000    com.apple.driver.AppleACPIPlatform (6.1) E44E285D-01ED-3E8B-A21D-FC792AFC9DB9 <14 13 12 8 7 6 5 3 1>
   16    6 0xffffff7f8135f000 0x30000    0x30000    com.apple.iokit.IONetworkingFamily (3.4) DD9C601F-FEC6-30BD-9EAD-6138651DCE9B <8 7 6 5 3 1>
   17    2 0xffffff7f818b5000 0x2d000    0x2d000    com.apple.iokit.IOTimeSyncFamily (700.7) 51BA0F9D-4C1A-39DD-9C7C-9508BB940F2F <16 6 5 3 1>
   18    9 0xffffff7f81a95000 0x7000     0x7000     com.apple.iokit.IOReportFamily (47) 5F165AE5-F4F2-3415-857C-34F2462A730E <6 5 3>
   19   10 0xffffff7f810e1000 0x28000    0x28000    com.apple.iokit.IOStorageFamily (2.1) 9B2E7108-AA17-3998-BF41-4B1297F455E5 <8 7 6 5 3 1>
   20    0 0xffffff7f81beb000 0x19000    0x19000    com.apple.driver.DiskImages (493.0.0) D685305F-622B-3E1D-B9A4-B569053DDDBD <19 8 7 6 5 3 1>
   21    5 0xffffff7f81a21000 0x7000     0x7000     com.apple.driver.IOSlaveProcessor (1) F034694F-AE67-3203-9F4F-49D032ECD703 <5 3>
   22    3 0xffffff7f824f2000 0x18000    0x18000    com.apple.driver.AppleSEPManager (1.0.1) 534324CB-A279-37CD-9210-88460434BEC3 <21 13 9 8 7 6 5 3 1>
   23    1 0xffffff7f811c9000 0x8000     0x8000     com.apple.driver.AppleBusPowerController (1.0) 660FC664-A61B-3B07-9178-32B80D4AF749 <14 12 7 6 5 3>
   24    5 0xffffff7f811d1000 0x8000     0x8000     com.apple.driver.usb.AppleUSBCommon (1.0) 8673619A-CA7C-3910-AD8E-17FF6A055872 <6 5 3 1>
   25    9 0xffffff7f811d9000 0x7b000    0x7b000    com.apple.iokit.IOUSBHostFamily (1.2) 437C62A8-4CBB-397F-92B9-766A06879E17 <24 23 8 7 6 5 3 1>
   26    3 0xffffff7f8125c000 0x1d000    0x1d000    com.apple.driver.KernelRelayHost (1) 4AD2FA2D-7618-3AB0-82D0-07317BA87816 <25 6 5 3>
   27    1 0xffffff7f8260f000 0x3f000    0x3f000    com.apple.driver.AppleCredentialManager (1.0) 7F048B65-E820-383B-A737-C0E1782CB801 <26 22 21 9 8 7 6 5 3 1>
   28    3 0xffffff7f80c4c000 0x2b000    0x2b000    com.apple.iokit.IOSCSIArchitectureModelFamily (408.200.1) 78083D37-80F2-3259-AA6D-773CAC7D5547 <7 6 5 3 1>
   29    1 0xffffff7f8127c000 0x19000    0x19000    com.apple.iokit.IOSCSIBlockCommandsDevice (408.200.1) 0A6C996C-B2A9-3F02-AB06-0FBA49294611 <28 19 7 6 5 3 1>
   30    1 0xffffff7f813a2000 0x2d000    0x2d000    com.apple.iokit.IOUSBMassStorageDriver (145.200.2) 22F8415D-76CF-3A73-A258-75D446C5EA65 <28 25 19 7 6 5 3 1>
   31    1 0xffffff7f810b5000 0xa000     0xa000     com.apple.kext.CoreTrust (1) 71A072F4-1292-3754-BD56-1922FA66D7E3 <9 5>
   32    6 0xffffff7f810bf000 0x1d000    0x1d000    com.apple.driver.AppleMobileFileIntegrity (1.0.5) A2492141-9480-3177-BC7D-455925BB4A2E <31 9 8 7 6 5 3 2 1>
   33    1 0xffffff7f824a9000 0x13000    0x13000    com.apple.driver.AppleUSBTDM (456.230.1) 98CD53E2-35E2-38D9-A776-460888CBBC08 <32 30 29 28 25 19 8 7 6 5 3 1>
   34    0 0xffffff7f8264e000 0x69000    0x69000    com.apple.driver.AppleKeyStore (2) 0357C2B9-D20F-3ABB-A0B2-C33EADADB78B <33 32 27 26 22 21 9 8 7 6 5 3 1>
   35    2 0xffffff7f82f9a000 0xc000     0xc000     com.apple.driver.AppleEffaceableStorage (1.0) B2BCF219-EACB-3908-883A-9ED52B0D75E1 <8 6 5 3 1>
   36    0 0xffffff7f82fa6000 0xc000     0xc000     com.apple.driver.AppleFDEKeyStore (28.30) E836E363-C65D-31EC-A71D-0EAEBF2290E2 <35 9 8 7 6 5 3 1>
   37    1 0xffffff7f831e3000 0x5000     0x5000     com.alexandred.VoodooI2CServices (1) 409F4A01-3D35-32FF-B7E5-DB77CB7F52AF <5 3>
   38    2 0xffffff7f831e8000 0x7a000    0x7a000    as.vit9696.Lilu (1.3.4) 05ADB6F6-0E55-3508-9627-E2BDA24AEE26 <8 6 5 3 2 1>
   39    0 0xffffff7f83262000 0x63000    0x63000    as.vit9696.WhateverGreen (1.2.6) 073AC103-5807-3374-8D23-F98A0975D391 <38 13 8 6 5 3 2 1>
   40    4 0xffffff7f832c5000 0x11000    0x11000    org.netkas.driver.FakeSMC (1800) FC7031CC-C949-35D1-AC1A-CA8DB349793E <12 8 6 5 3 1>
   41    0 0xffffff7f832d6000 0x102000   0x102000   as.vit9696.AppleALC (1.3.5) A9BD8D90-DD4E-3E90-A146-57F4375554C2 <38 13 8 6 5 3 2 1>
   42    0 0xffffff7f833d8000 0x5000     0x5000     org.hwsensors.driver.CPUSensors (1800) ED90DA0F-5876-3DB5-82EC-CEEA470A7479 <40 8 6 5 3>
   43    0 0xffffff7f80f88000 0x2000     0x2000     com.apple.security.TMSafetyNet (8) 298CDE1E-4536-3CE8-B9EE-C77CCD9C05E9 <8 7 6 5 2 1>
   44    2 0xffffff7f810dc000 0x5000     0x5000     com.apple.kext.AppleMatch (1.0.0d1) 1A0A5887-F79C-3086-BC7D-3FBB7C148D6F <5 1>
   45    2 0xffffff7f81111000 0x31000    0x31000    com.apple.security.sandbox (300.0) 7A7E863E-B351-3327-9B63-A47B70753306 <44 32 19 8 7 6 5 3 2 1>
   46    1 0xffffff7f81142000 0x8000     0x8000     com.apple.security.quarantine (3) F9CE3703-C975-31CD-B19F-ED2FD32237F6 <45 44 8 7 6 5 2 1>
   47    0 0xffffff7f831d8000 0x9000     0x9000     com.apple.nke.applicationfirewall (190) A54B1C0C-8626-3D7E-BAA4-C4A460B4568E <8 7 6 5 3 1>
   48    0 0xffffff7f82fe1000 0x3000     0x3000     com.apple.driver.AppleAPIC (1.7) 02950A63-A9EC-3F20-B25A-25A6122CB4E1 <13 5 3>
   49    0 0xffffff7f82524000 0x4000     0x4000     com.apple.driver.AppleSMBIOS (2.1) D7ACC841-2BD9-38EF-A58F-49BF9EF516CC <8 5 3>
   50    0 0xffffff7f833de000 0x3000     0x3000     org.hwsensors.driver.SMMSensors (1800) 97DDF4ED-310B-3123-988E-E1A9890743A6 <40 8 6 5 3>
   51   17 0xffffff7f81b83000 0x4b000    0x4b000    com.apple.iokit.IOGraphicsFamily (530.14) D44517BE-2B53-3BD5-826E-4E78B55E3B73 <13 8 6 5 3 1>
   52    5 0xffffff7f81bdb000 0x10000    0x10000    com.apple.iokit.IONDRVSupport (530) 693B770C-4748-33DC-B497-CF8C103DDD0E <51 13 8 6 5 3>
   53    1 0xffffff7f82fd3000 0x6000     0x6000     com.apple.driver.AppleBacklightExpert (1.1.0) 359BE0FA-3E1D-3D0F-A338-AB9B957C4424 <52 51 14 13 6 5 3>
   54    0 0xffffff7f82fd9000 0x5000     0x5000     com.apple.driver.AppleBacklight (170.12.11) 253D68ED-4796-3B60-9034-2AB28258DA78 <53 52 51 13 6 5 3>
   55    3 0xffffff7f833e2000 0xb000     0xb000     org.rehabman.voodoo.driver.PS2Controller (1.8.34) FE68E3D5-29E0-346A-9036-090411302A58 <12 8 6 5 3 1>
   56    0 0xffffff7f82bbd000 0x3000     0x3000     com.apple.driver.AppleHPET (1.8) 784E4E15-3762-3886-9A11-33AF0A9810C1 <12 8 6 5 3>
   57   12 0xffffff7f81497000 0x7e000    0x7e000    com.apple.iokit.IOHIDFamily (2.0.0) 7379360B-DC22-3783-A148-2D10C62D11A8 <8 7 6 5 3 2 1>
   58    2 0xffffff7f81a18000 0x4000     0x4000     com.apple.iokit.IOSMBusFamily (1.1) BC6BE924-53E3-318A-A1B7-B896FA559717 <6 5 3>
   59    0 0xffffff7f830ae000 0x7000     0x7000     com.apple.driver.AppleACPIEC (6.1) 6C019704-A39A-3916-82AC-5700B64A2509 <58 57 18 15 12 8 7 6 5 3 1>
   60    0 0xffffff7f82556000 0x8000     0x8000     com.apple.driver.AppleRTC (2.0) 2C17000F-F1B9-3286-8D53-89DB8D4D92B7 <12 8 6 5 3 1>
   61    0 0xffffff7f833ed000 0x9000     0x9000     org.rehabman.driver.AppleSmartBatteryManager (1.90) 0EE476DC-884B-35FF-BD9E-E24BEC25A521 <12 5 3>
   62    1 0xffffff7f81af2000 0x5000     0x5000     com.apple.driver.AppleEFIRuntime (2.1) 5D2F3E1A-5A35-3248-8AD0-E6AB125619F2 <8 7 6 5 3>
   63    0 0xffffff7f830b8000 0x4000     0x4000     com.apple.driver.AppleACPIButtons (6.1) 7F323351-4955-37FB-8D3A-D281FDB4B805 <57 18 15 12 8 7 6 5 3 1>
   64    0 0xffffff7f833f9000 0x8000     0x8000     org.hwsensors.driver.ACPISensors (1800) FA4DF6C0-0D3A-3CE2-8569-0AB2C84053E7 <40 12 8 6 5 3>
   65    1 0xffffff7f83403000 0xd000     0xd000     org.coolstar.VoodooGPIO (1.1) 125807B8-4E2E-341B-AE46-F06983D562A3 <12 6 5 3>
   66    2 0xffffff7f81af7000 0xb000     0xb000     com.apple.driver.AppleEFINVRAM (2.1) 328FCBD7-8C2C-3A4A-AF92-9270C1403891 <62 8 7 6 5 3 1>
   67    0 0xffffff7f811c4000 0x3000     0x3000     com.apple.private.KextAudit (1.0) 839C96EF-22F0-3C23-8207-A11493EA0054 <14 8 7 6 5 3>
   68    1 0xffffff7f81537000 0x56000    0x56000    com.apple.driver.usb.AppleUSBXHCI (1.2) 69030E8B-96D7-3417-930D-0F27A6082E95 <25 24 12 8 7 6 5 3 1>
   69    0 0xffffff7f81594000 0x2f000    0x2f000    com.apple.driver.usb.AppleUSBXHCIPCI (1.2) 494BC1E0-C31B-36A2-843D-0B6A5BB91EA1 <68 25 24 13 12 8 7 6 5 3 1>
   70    1 0xffffff7f83410000 0x2e000    0x2e000    com.alexandred.VoodooI2C (2.1.4) E7230338-1AFE-3830-B753-09751D6BABA3 <65 57 37 13 12 6 5 3 1>
   71    1 0xffffff7f82029000 0x1a000    0x1a000    com.apple.iokit.IOAHCIFamily (288) 5D28C137-976F-3FA6-B33C-9A08B6621F24 <6 5 3 1>
   72    0 0xffffff7f82fe6000 0x14000    0x14000    com.apple.driver.AppleAHCIPort (329.200.2) 798B4D67-6CC7-381E-9C3A-3A6FE412375A <71 13 6 5 3 1>
   73    0 0xffffff7f8343e000 0xd000     0xd000     org.hwsensors.driver.LPCSensors (1800) EF5BB9DC-C33F-3EED-9F96-42A7F22D806F <40 13 12 8 6 5 3>
   74    0 0xffffff7f8344b000 0x67000    0x67000    com.insanelymac.RealtekRTL8111 (2.2.2) 24D129C7-C25C-3D7B-9E10-EA71D9BE6511 <16 13 6 5 3 1>
   75    0 0xffffff7f81b02000 0x40000    0x40000    com.apple.iokit.IONVMeFamily (2.1.0) ABA6DFDD-AC72-3008-83FE-EF9722E66FEB <66 32 19 18 13 8 7 6 5 3 1>
   76    0 0xffffff7f82216000 0xa000     0xa000     com.apple.driver.AppleXsanScheme (3) FAA058FC-526F-39DC-B336-4443C3F2773E <19 6 5 3 1>
   77    0 0xffffff7f830c0000 0x100000   0x100000   com.apple.filesystems.apfs (945.241.4) 4C147D98-F411-3D19-99D0-6778CC579FE9 <35 19 9 8 7 6 5 3 1>
   78    0 0xffffff7f834b2000 0x6000     0x6000     org.rehabman.voodoo.driver.PS2Keyboard (1.8.34) 454845C4-36AE-37F0-995E-961CAAF609FB <57 55 18 8 7 6 5 3 1>
   79    0 0xffffff7f834b8000 0xc000     0xc000     org.rehabman.voodoo.driver.PS2Trackpad (1.8.28) 5098823E-03FD-3E78-B46A-1E5C01D095D5 <57 55 18 8 7 6 5 3 1>
   80    0 0xffffff7f834c4000 0x4000     0x4000     org.rehabman.voodoo.driver.PS2Mouse (1.8.28) B050FBE3-C360-3C9D-8E5D-6239F6AAC04F <57 55 6 5 3>
   81    1 0xffffff7f813d6000 0x9b000    0x9b000    com.apple.iokit.IOUSBFamily (900.4.2) DE775B13-AD71-3FC6-B9E6-30B4B6DCC9D6 <25 24 13 8 6 5 3 1>
   82    0 0xffffff7f816d8000 0x5000     0x5000     com.apple.driver.usb.AppleUSBHostPacketFilter (1.0) C12AA28D-C393-3AA1-ABF3-6506ABB8248F <25 24 8 7 6 5 3 1>
   83    1 0xffffff7f8207e000 0x8000     0x8000     com.apple.filesystems.hfs.encodings.kext (1) A5FC0D67-8BFA-3B5B-AB73-1A07DDF2C200 <8 7 6 5 3 1>
   84    1 0xffffff7f82086000 0x69000    0x69000    com.apple.filesystems.hfs.kext (407.200.4) C802AB49-117F-3215-868B-CDC96BB3D1CF <83 8 7 6 5 3 1>
   85    0 0xffffff7f821f3000 0xe000     0xe000     com.apple.BootCache (40) 27AC572D-B4B0-3D33-BCBB-E6D58D22A10D <8 7 6 5 3 1>
   86    2 0xffffff7f81a30000 0xe000     0xe000     com.apple.iokit.IOSerialFamily (11) 455F1C71-4ADD-3FD3-B4C2-4B28EC7A3287 <8 7 6 5 3 1>
   87    0 0xffffff7f82224000 0x13000    0x13000    com.apple.driver.AppleVirtIO (2.1.3) 86BDC409-75C3-3166-8C04-3722C6EE39F5 <86 19 13 6 5 3 1>
   88    0 0xffffff7f82455000 0x8000     0x8000     com.apple.AppleSystemPolicy (1.0) 4B3B2953-B64C-3C1C-AB04-C507E580E3EE <46 45 32 8 7 6 5 3 2 1>
   89    0 0xffffff7f82f61000 0xd000     0xd000     com.apple.AppleFSCompression.AppleFSCompressionTypeZlib (1.0.0) 105AF50D-B2F3-33C2-97E7-563EEAFB3AB5 <7 5 3 2 1>
   90    0 0xffffff7f82f71000 0x3000     0x3000     com.apple.AppleFSCompression.AppleFSCompressionTypeDataless (1.0.0d1) B09FB9C2-9CA4-3C80-9540-B4CEAB2D9AD0 <8 7 5 3 2 1>
   91    0 0xffffff7f82f96000 0x2000     0x2000     com.apple.driver.AppleFileSystemDriver (3.0.1) 27100F01-AA28-3BC2-AE1E-6FAD45570291 <19 5 3>
   92    0 0xffffff7f834c8000 0x11000    0x11000    com.alexandred.VoodooI2CHID (1) 0C2FCF61-54DA-3FE5-99E3-B9E62A0AC8D2 <70 57 51 12 6 5 3>
   93    1 0xffffff7f82342000 0x17000    0x17000    com.apple.driver.AppleInputDeviceSupport (2410.2) 441AA101-838F-3975-977C-E5AD3BB05317 <21 6 5 3 1>
   94    1 0xffffff7f8235d000 0x27000    0x27000    com.apple.driver.AppleMultitouchDriver (2410.5) 48943471-CF37-316A-88D4-C8CA249AB2C2 <93 57 18 8 6 5 3 1>
   95    2 0xffffff7f81c98000 0xf6000    0xf6000    com.apple.iokit.IOBluetoothFamily (6.0.10f1) 89233641-FD29-38DB-A84B-3176103C3B88 <25 18 12 8 7 6 5 3 1>
   96    1 0xffffff7f82397000 0x1a000    0x1a000    com.apple.driver.IOBluetoothHIDDriver (6.0.10f1) FC4E8BB4-8A0D-3A50-83FC-448EC33B9C7A <95 57 6 5 3>
   97    1 0xffffff7f823b3000 0xe000     0xe000     com.apple.driver.AppleHSBluetoothDriver (138.2) E624A110-C40D-3FB2-A53D-AD8B35576CF1 <96 95 57 7 6 5 3 1>
   98    0 0xffffff7f823c3000 0xa000     0xa000     com.apple.driver.AppleTopCaseHIDEventDriver (138.2) 62A890AC-EC73-3993-B8EC-02786F44AB48 <97 94 57 7 6 5 3 1>
   99    5 0xffffff7f81a9c000 0xa000     0xa000     com.apple.driver.IOPlatformPluginFamily (6.0.0d8) FCD12012-BC9D-3F1F-8FB6-9BB79C543053 <12 8 7 6 5 3>
  100    1 0xffffff7f81aa6000 0x18000    0x18000    com.apple.driver.X86PlatformPlugin (1.0.0) F6F851FC-2BAB-3C18-8E7F-AE0DB1AC153C <99 81 25 14 12 8 7 6 5 3 1>
  101    0 0xffffff7f825b5000 0x4000     0x4000     com.apple.driver.AppleOSXWatchdog (1) 33C5CEEB-0139-3C6F-BF4D-F2EBA885F264 <13 8 7 6 5 3 1>
  102    2 0xffffff7f819f4000 0x22000    0x22000    com.apple.iokit.IOSurface (255.1) 12B5957C-3874-3A96-8FC6-FAC2180790A9 <8 7 6 5 3 1>
  103    2 0xffffff7f82717000 0xa5000    0xa5000    com.apple.iokit.IOAcceleratorFamily2 (404.2.2) 3F0DBC5F-414B-379E-8C7B-A2F50B278A2A <102 51 32 18 13 8 7 6 5 3 1>
  104    5 0xffffff7f82941000 0x9000     0x9000     com.apple.AppleGraphicsDeviceControl (3.28.4) E80DEB91-2401-31C2-901F-CA63B4342337 <51 13 8 7 6 5 3 1>
  105    0 0xffffff7f8294c000 0x203000   0x203000   com.apple.driver.AppleIntelCFLGraphicsFramebuffer (12.0.4) 62299C05-41B5-3538-AAC5-C53551ADEB7E <104 103 51 18 13 12 8 7 6 5 3 1>
  106    1 0xffffff7f81a1c000 0x5000     0x5000     com.apple.iokit.IOSlowAdaptiveClockingFamily (1.0.0) DB030CF2-B474-3D97-969D-C3042CA5A704 <8 7 6 5 3 1>
  107    0 0xffffff7f826c4000 0x2000     0x2000     com.apple.driver.AppleIntelSlowAdaptiveClocking (4.0.0) 004E56BA-FEA3-381D-817C-9BBDBC021A9D <106 5 3>
  108    0 0xffffff7f80dc9000 0x4000     0x4000     com.intel.driver.EnergyDriver (3.5.5) 60449181-1B5B-374C-84C4-F81DDE69DAF8 <8 6 5 3>
  109    0 0xffffff7f82eae000 0xd000     0xd000     com.apple.AppleGPUWrangler (3.28.4) 81D2E775-ABB6-31A9-AD44-7D6ABC644618 <104 51 13 8 7 6 5 3 1>
  110    0 0xffffff7f82b7c000 0x9000     0x9000     com.apple.driver.AppleHV (1) 1D2CA5D2-25F9-35A2-AACD-2819C15B613A <8 7 6 5 3 1>
  111    0 0xffffff7f8250d000 0xd000     0xd000     com.apple.driver.AppleSSE (1.0) EAA88574-9115-373B-A5DF-F86FEA5EDD14 <26 22 21 8 6 5 3 1>
  112    0 0xffffff7f820f6000 0x5000     0x5000     com.apple.Dont_Steal_Mac_OS_X (7.0.0) E8A46A07-5CA9-3449-AB3C-194D7EDBDEC6 <14 9 8 5 3 1>
  113    2 0xffffff7f81f10000 0x7000     0x7000     com.apple.iokit.IOEthernetAVBController (1.1.0) AB7E6B6B-810E-31E8-9974-772E2429C3E3 <16 6 5 3 1>
  114    1 0xffffff7f81f17000 0x9b000    0x9b000    com.apple.plugin.IOgPTPPlugin (700.7) C55991D3-9D47-33FB-894A-7DA24DC705E0 <113 57 17 16 11 7 6 5 3 1>
  115    0 0xffffff7f81fc5000 0x10000    0x10000    com.apple.iokit.IOAVBFamily (710.1) 3845EF61-E120-38A5-AA2C-DB7434026A75 <114 113 17 16 7 6 5 3 1>
  116    0 0xffffff7f81c88000 0xa000     0xa000     com.apple.iokit.IOBluetoothSerialManager (6.0.10f1) 1BAB5621-A7D3-323D-B3E1-EFC51FE8B69D <86 8 6 5 3 1>
  117    0 0xffffff7f81396000 0x6000     0x6000     com.apple.iokit.IOUserEthernet (1.0.1) 553C14F4-5F74-3F43-B040-8EF903401E56 <16 7 6 5 3 1>
  118    0 0xffffff7f81161000 0x12000    0x12000    com.apple.driver.pmtelemetry (1) C9FFBA9E-710C-3CC1-A95C-0D384566669F <8 7 6 5 3>
  119    0 0xffffff7f82521000 0x3000     0x3000     com.apple.driver.AppleSMBusPCI (1.0.14d1) DC2BC40C-FC0E-3A6C-A5E8-589D26D0D6AA <13 6 5 3>
  120    1 0xffffff7f81ac7000 0x12000    0x12000    com.apple.driver.IOPlatformPluginLegacy (1.0.0) 9FD09387-9EF6-3A87-AED0-CE2230C6ECA2 <99 12 8 7 6 5 3>
  121    0 0xffffff7f81adb000 0x10000    0x10000    com.apple.driver.ACPI_SMC_PlatformPlugin (1.0.0) D0D3C7FE-0934-3D27-A4B8-60C2D18C94E4 <120 99 14 13 12 8 7 6 5 3>
  122    2 0xffffff7f81740000 0xce000    0xce000    com.apple.vecLib.kext (1.2.0) 990BDF56-F253-3E2A-89DB-7914D4074AAB <11 7 6 5 3>
  123    5 0xffffff7f8180e000 0x3f000    0x3f000    com.apple.iokit.IOAudioFamily (206.5) 99F194F6-E536-3B60-9667-06F6F83BC26B <122 6 5 3 1>
  124    0 0xffffff7f82ebf000 0x70000    0x70000    com.apple.driver.AppleGFXHDA (100.1.40) E99DD10D-EEE9-3FD1-A2FB-519DE4B97B46 <123 52 51 13 8 7 6 5 3 1>
  125    2 0xffffff7f82bd7000 0xc000     0xc000     com.apple.iokit.IOHDAFamily (282.10) 8C9B1B23-655F-3091-B6C3-6EF85ECCDC67 <6 5 3 1>
  126    1 0xffffff7f82bea000 0x1d000    0x1d000    com.apple.driver.AppleHDAController (282.10) 7EF94F9C-FF19-3168-943B-CC7A3D77B1D2 <125 123 51 13 8 7 6 5 3 1>
  127    0 0xffffff7f827cc000 0xf3000    0xf3000    com.apple.driver.AppleIntelKBLGraphics (12.0.4) FC447A62-ADF3-3583-B929-6F4D6CB38A3E <103 102 51 13 8 7 6 5 3 1>
  128    0 0xffffff7f82ebb000 0x3000     0x3000     com.apple.AGDCPluginDisplayMetrics (3.28.4) D34E781E-7E6B-3110-B30A-4387D3244485 <104 8 7 6 5 3 1>
  129    0 0xffffff7f82f75000 0x3000     0x3000     com.apple.driver.AppleFIVRDriver (4.1.0) 79822728-9984-38A9-9063-9BD9DCD44850 <5 3>
  130    1 0xffffff7f82e97000 0x3000     0x3000     com.apple.driver.AppleGraphicsControl (3.28.4) B940D328-A2B1-3906-972C-289E86DFDE48 <8 6 5 3 1>
  131    0 0xffffff7f82e9a000 0x12000    0x12000    com.apple.driver.AppleGraphicsDevicePolicy (3.28.4) 3F3BF598-E8D7-3D0F-9336-6646C547F0DB <130 104 51 13 12 8 7 6 5 3 1>
  132    1 0xffffff7f82c09000 0x13000    0x13000    com.apple.kext.OSvKernDSPLib (527) C39D546B-2D04-3E1E-A96F-9A478137270E <6 5>
  133    1 0xffffff7f82c1c000 0x142000   0x142000   com.apple.driver.DspFuncLib (282.10) 1FF47E6F-AD74-32FB-8D2E-BDF93CC70ED3 <132 123 122 66 7 6 5 3 1>
  134    0 0xffffff7f82d69000 0xb7000    0xb7000    com.apple.driver.AppleHDA (282.10) 0E41E3D3-0B7A-3BE5-A104-3A2E1CE5DCC9 <133 126 125 123 52 51 7 6 5 3 1>
  135    1 0xffffff7f825c2000 0xe000     0xe000     com.apple.driver.AppleSMBusController (1.0.18d1) A3CC320C-0DB3-3595-A220-A3B6FF52209B <58 13 12 6 5 3>
  136    0 0xffffff7f825d3000 0xf000     0xf000     com.apple.driver.AppleMCCSControl (1.5.6) 5DDA7866-6DFC-3695-8871-FAC1CCB4F784 <135 51 14 13 12 8 6 5 3 1>
  137    0 0xffffff7f82339000 0x5000     0x5000     com.apple.driver.AppleUpstreamUserClient (3.6.5) 8305F4FC-DD16-3C14-AAD2-D1073CFA9071 <51 13 12 8 6 5 3 1>
  138    0 0xffffff7f82be6000 0x2000     0x2000     com.apple.driver.AppleHDAHardwareConfigDriver (282.10) 19C0592A-80DA-3DCE-9E8E-2F458D31F709 <5 3>
  139    1 0xffffff7f81abe000 0x7000     0x7000     com.apple.driver.X86PlatformShim (1.0.0) F6B0D2FB-F24D-3061-A858-416BB4DEBEA4 <100 99 14 8 5 3>
  140    0 0xffffff7f82e75000 0x19000    0x19000    com.apple.driver.AGPM (110.23.46) 4789EB94-7E61-317B-9CCF-3800C02F363F <104 99 52 51 13 7 6 5 3>
  141    0 0xffffff7f825ae000 0x4000     0x4000     com.apple.driver.ApplePlatformEnabler (2.7.0d0) 5DD97FD6-6D2C-33E8-AEAB-C91CEE3D0785 <8 6 5 3>
  142    1 0xffffff7f81044000 0x5000     0x5000     com.apple.kext.triggers (1.0) 491A8A76-3FCF-3B86-8906-A4796ED87102 <8 7 6 5 3 1>
  143    0 0xffffff7f82203000 0x9000     0x9000     com.apple.filesystems.autofs (3.0) 5D1B09EB-3D8D-38A5-9561-40B0A8CDA450 <142 8 7 6 5 3 2 1>
  144    0 0xffffff7f834d9000 0x17000    0x17000    com.tuxera.filesystems.tuxera_ntfs (2017.12.18) 8425857F-FADB-51B7-50A3-30DB7629D80D <8 6 5 3 1>
  145    0 0xffffff7f8220e000 0x5000     0x5000     com.apple.driver.AudioAUUC (1.70) 1C1CC4A3-DA08-3921-8103-036A9046C22B <123 51 13 12 8 6 5 3 1>
  146    0 0xffffff7f82f7a000 0x18000    0x18000    com.apple.fileutil (18.306.12) 5E0468C0-F2DE-37EF-BB2A-0796BA8311B9 <6 5 3 2 1>`

**Comment by kirainmoe** [comment]
1. 使用的是否为本仓库里提供的 config.plist？如果不是，请提供 SMBIOS 型号。
2. 使用 sudo kextcache -i 重建缓存，Clover 添加 -f 参数确保驱动安装并成功重建。
3. 如果驱动正确加载，在 IORegistryExplorer 软件中搜索 XHC, 应该能看到 HS02, HS04, HS06而没有 HS01 和 HS03。

请按照上面的步骤排除问题，然后进一步报告。

**Comment by kirainmoe** [comment]
如果问题依旧，方便的话请找个地方上传问题描述文件，至少包括 IORegistry Explorer 的导出和当前EFI文件夹。或者如果能参照 tonymacx86 论坛的 Problem reporting file 的格式更好。

**Comment by jkdep001** [comment]
{product model :"MacBookPro15,2", bios:"MBP152.88Z.F000.B00.1809171524"}

**Comment by kirainmoe** [comment]
我也不知道是什么问题，试试按这里的教程https://blog.daliansky.net/Intel-FB-Patcher-USB-Custom-Video.html 重新定制一下 USBPorts.kext 吧，hs04 09 12 ss01 05 06 type 为 0x3，hs10 为 0xa，ss03 为 0x9，保留hs 02,04,06,09-14; ss01, 03, 05, 06; usr1, 2其它全为 0xff……我再研究一下其它的方法。

**Comment by kirainmoe** [comment]
最新的提交已经把 USBPorts 改为 USBInjectAll + SSDT-UIAC.aml 驱动，试一下新的 EFI 看看还有没有问题。
