### ISSUE TITLE
遇到一些问题

### ISSUE THREAD

**Issue by 0x112** [kirainmoe/hasee-z7-kp7gz-macos#20]
机型是Z7M-KP7GZ
1. 安装完替换EFI之后，开机，按电源键没反应，不应该是按一下就休眠吗？
2. 使用Addons/optimize.sh的脚本开启HiDPI，无论注入或者不注入EDID，睡眠之后唤醒都是1/4屏，请问应该如何修复呢？

**Comment by kirainmoe** [comment]
神舟的按键 ACPI 表与普通苹果电脑不同，按电源键并不会触发休眠，可以使用 Fn+F1 键代替。

HIDPI 四分之一屏问题无法解决，唯一的方案是将分辨率设为 1920x1080. 但问题来了，设成 1920x1080 开启 HIDPI 并没有意义。

**Comment by 0x112** [comment]
我刚刚用一键HiDPI脚本，不注入EDID的方式开启HiDPI，手动指定分辨率为1600x900 1440x810 1424x802，可以被休眠唤醒，而且不花屏。
另外，想问下您目前用的HiDPI方案是？

**Comment by 0x112** [comment]
我还想问下，黑苹果登录iCloud会不会导致账号被封？我iPhone也登录了相同的账号

**Comment by kirainmoe** [comment]
我不开 HIDPI，如果实在像我一样看不清字，可以用 DarwinDumper 提取 EDID + FixEDID 修复 EDID，然后注入 EDID 并且使用 RDM 调节分辨率到 1600x900。具体可以网上搜索教程：DarwinDumper+FixEDID.

登录 iCloud 不会封号。
