### ISSUE TITLE
声卡使用AppleAlc.kext驱动极其不稳定

### ISSUE THREAD

**Issue by jkdep001** [kirainmoe/hasee-z7-kp7gz-macos#3]
[声卡使用AppleAlc.kext驱动极其不稳定，声卡id也注入了88，{layout-id，88，number}

**Comment by kirainmoe** [comment]
极其不稳定如何体现？我这里一切正常，外放、麦克风、耳机全部可用，没有办法定义你说的不稳定。如果你认为声卡部分确实有问题，请尝试注入 layout-id 29？

**Comment by jkdep001** [comment]
声卡，经常出现开机小喇叭是灰色（就是用不了），然后重启启动几次又又可能正常，但是只要关机了都有可能出现声卡不起作用（试过，88，30，58的layout-id）均会出现这种问题，麻烦分析一下，感谢！！！

**Comment by kirainmoe** [comment]
小喇叭为灰色说明声卡驱动 AppleALC.kext 可能没有正确加载，请使用 Kext Wizard 或终端输入 sudo kextstats 查看 AppleALC.kext 是否正确加载，如果没有，则将 Kexts 文件夹下的 AppleALC.kext 安装到 /L/E 或 /S/L/E 下，重建缓存即可。

**Comment by jkdep001** [comment]
第三天重启小喇叭不是灰色能用了，查询字段显示：
`42    0 0xffffff7f832c2000 0x102000   0x102000   as.vit9696.AppleALC (1.3.5) A9BD8D90-DD4E-3E90-A146-57F4375554C2 <38 13 8 6 5 3 2 1>`
代表加载成功了吗？

**Comment by kirainmoe** [comment]
这样说明驱动已经加载了。如果你更改EFI/CLOVER/Kexts/Others下的文件，可能会导致不加载该驱动，此时再按上面说的解决就行了。
