### ISSUE TITLE
关于独显驱动问题

### ISSUE THREAD

**Issue by L0ngxhn** [kirainmoe/hasee-z7-kp7gz-macos#5]
我朋友说在10.13.6 特供版下， 装WebNV是可以外屏驱动独显的。但是接HDMI时会出现睡眠问题（无法睡眠，2s自动唤醒，风扇暴走）

**Comment by kirainmoe** [comment]
这台机子用的同方模具的 HDMI 是直连独显的，因此在 10.13.6 能安装 Nvidia Webdriver 的情况下理论上可能可以外接 HDMI 驱动独显。但是我没有试过 10.13.6 特供版，而且我也没有外置显示器能测试 HDMI，所以我没有办法知道到底可不可行。至于 HDMI 导致睡眠问题单凭描述我也无法知道原因，可以用 pmset -g log 排查一下。目前只能等 10.14 的 webdriver 出来再做进一步的尝试了。

**Comment by kirainmoe** [comment]
（另外，如果你的朋友在 z7-kp7gz 上成功驱动 DGPU 的话，不妨把 EFI 也分享一下）

**Comment by L0ngxhn** [comment]
链接：https://pan.baidu.com/s/1lUw7qALcqy8ZddS7tHIpaw 
提取码：kvtl

**Comment by kirainmoe** [comment]
.......这，且不说型号根本不一样了...kp7sc是蓝天模具，跟同方模具天差地别...

**Comment by L0ngxhn** [comment]
emmm，真的吗，不好意思。搞错了哦。哈哈哈，抱歉~
