### ISSUE TITLE
Z7M-KP7Z 已装上。但目前还存在一点问题……

### ISSUE THREAD

**Issue by zxj5470** [kirainmoe/hasee-z7-kp7gz-macos#6]
明天再研究……

果然还是电源驱动问题……

**Comment by kirainmoe** [comment]
亮度问题，加载 SSDT-PNLFCFL.aml，取消勾选 Clover FixMask 中的 Add PNLF，安装最新版 lilu＋whatever green＋applebacklightfixup，删除 igfxcflbklt 引导参数就 ok。

小键盘无解，估计原本就是这么设定的。

设置触摸板手势前必须驱动电池。

**Comment by zxj5470** [comment]
手贱把仓库里面的驱动全部复制进去……现在炸了233333

**Comment by zxj5470** [comment]
手头上有一台苹果，就这么玩了23333
![image](https://user-images.githubusercontent.com/20026798/54100727-fd2d4c00-43fa-11e9-8802-cc31b6735704.png)
![image](https://user-images.githubusercontent.com/20026798/54100728-01596980-43fb-11e9-87b3-9ef67663681f.png)

**Comment by kirainmoe** [comment]
= =所以呢，怎么个炸法

**Comment by zxj5470** [comment]
具体大概是苹果加载进度条大概到70%然后黑屏。。。
大概不可以一次性把kext都丢进去吧23333……

**Comment by kirainmoe** [comment]
黑屏的时候等三分钟进系统，看看 AppleBacklightFixup 加载了没有。另外，确定你把 SSDT-PNLFCFL.aml 丢进 ACPI/patched 并且在 Clover 的 SSDT SortOrder 加入该文件。

触摸板部分检查 VoodooI2C.kext, VoodooI2CHID.kext, VoodooI2CService.kext, VoodooGPIO.kext 是否正确加载，后面两个 Kext 是包含在 VoodooI2C.kext 中的依赖。

**Comment by zxj5470** [comment]
现在有意思了……我有两个efi，
一个是之前装的，有线网卡的驱动，没有电源图标。
另一个是现在U盘里面的EFI（master分支的内容），能显示出电源图标。但是没有有线网卡驱动23333……
我把两个整合一下23333

另外我发现用U盘EFI拿来boot，U盘没法挂载。还好我有两台电脑两个U盘（滑稽

**Comment by kirainmoe** [comment]
那可能是我少提交了什么驱动....？我晚上再检查一下，有些 kext 被我装到 L/E 去了，我可能没弄上来那些。

**Comment by zxj5470** [comment]
我另一个U盘是PE……
左边的 `M` 盘是硬盘里面的EFI，右边的 `I` 盘是用来启动的U盘的EFI
那个8168H是我自作聪明改动名字……
![image](https://user-images.githubusercontent.com/20026798/54101809-7e3b1200-4400-11e9-9aa6-c4cab41f7ceb.png)

**Comment by zxj5470** [comment]
```bash
zhs-MacBook-Pro:~ zh$ kextstat |grep Voodoo
   39    1 0xffffff7f825f6000 0x5000     0x5000     com.alexandred.VoodooI2CServices (1) 409F4A01-3D35-32FF-B7E5-DB77CB7F52AF <5 3>
   63    1 0xffffff7f8272b000 0xd000     0xd000     org.coolstar.VoodooGPIO (1.1) 125807B8-4E2E-341B-AE46-F06983D562A3 <12 6 5 3>
   68    0 0xffffff7f82738000 0x2e000    0x2e000    com.alexandred.VoodooI2C (2.1.4) E7230338-1AFE-3830-B753-09751D6BABA3 <63 56 39 13 12 6 5 3 1>
```

**Comment by zxj5470** [comment]
全部的：
```bash
zhs-MacBook-Pro:~ zh$ kextstat |grep -v com.apple
Index Refs Address            Size       Wired      Name (Version) UUID <Linked Against>
   37    3 0xffffff7f82572000 0x21000    0x21000    as.vit9696.Lilu (1.3.2) 4C06EC29-2946-3A2A-806F-5C3BDA505597 <8 6 5 3 2 1>
   38    0 0xffffff7f82593000 0x63000    0x63000    as.vit9696.WhateverGreen (1.2.7) D16E06DB-10FD-39A0-9417-B40FE4CC8EB7 <37 13 8 6 5 3 2 1>
   39    1 0xffffff7f825f6000 0x5000     0x5000     com.alexandred.VoodooI2CServices (1) 409F4A01-3D35-32FF-B7E5-DB77CB7F52AF <5 3>
   40    0 0xffffff7f825fb000 0x4000     0x4000     com.rehabman.driver.USBInjectAll (0.7.1) A5767EA0-3760-3131-B996-28EE85139CF5 <13 12 5 3>
   41    4 0xffffff7f82600000 0x11000    0x11000    org.netkas.driver.FakeSMC (1800) FC7031CC-C949-35D1-AC1A-CA8DB349793E <12 8 6 5 3 1>
   42    0 0xffffff7f82611000 0x5000     0x5000     org.vanilla.driver.CPUFriend (1.1.4) BB35C499-1A39-38C2-9DA7-CD978118909B <37 12 8 6 5 3 2 1>
   43    0 0xffffff7f82616000 0xea000    0xea000    as.vit9696.AppleALC (1.3.4) 5A1678E9-EEB8-3646-9244-5B589288D960 <37 13 8 6 5 3 2 1>
   44    0 0xffffff7f82700000 0x9000     0x9000     org.rehabman.driver.AppleSmartBatteryManager (1.81.4) 2B852534-CAC2-3E36-BF21-C10984081B74 <12 5 3>
   45    0 0xffffff7f8270c000 0x5000     0x5000     org.hwsensors.driver.CPUSensors (1800) ED90DA0F-5876-3DB5-82EC-CEEA470A7479 <41 8 6 5 3>
   53    0 0xffffff7f82712000 0x3000     0x3000     org.hwsensors.driver.SMMSensors (1800) 97DDF4ED-310B-3123-988E-E1A9890743A6 <41 8 6 5 3>
   60    3 0xffffff7f82716000 0xb000     0xb000     org.rehabman.voodoo.driver.PS2Controller (1.9.2) E11711CB-AFEA-384E-97B8-B8EECB515995 <12 8 6 5 3 1>
   62    0 0xffffff7f82721000 0x8000     0x8000     org.hwsensors.driver.ACPISensors (1800) FA4DF6C0-0D3A-3CE2-8569-0AB2C84053E7 <41 12 8 6 5 3>
   63    1 0xffffff7f8272b000 0xd000     0xd000     org.coolstar.VoodooGPIO (1.1) 125807B8-4E2E-341B-AE46-F06983D562A3 <12 6 5 3>
   68    0 0xffffff7f82738000 0x2e000    0x2e000    com.alexandred.VoodooI2C (2.1.4) E7230338-1AFE-3830-B753-09751D6BABA3 <63 56 39 13 12 6 5 3 1>
   71    0 0xffffff7f82766000 0xd000     0xd000     org.hwsensors.driver.LPCSensors (1800) EF5BB9DC-C33F-3EED-9F96-42A7F22D806F <41 13 12 8 6 5 3>
   73    0 0xffffff7f82773000 0x18000    0x18000    net.osx86.kexts.GenericUSBXHCI (1.2.11) no UUID <72 13 8 6 5 3>
   74    0 0xffffff7f8278b000 0x67000    0x67000    com.insanelymac.RealtekRTL8111 (2.2.2) 24D129C7-C25C-3D7B-9E10-EA71D9BE6511 <17 13 6 5 3 1>
   78    0 0xffffff7f827f5000 0x6000     0x6000     org.rehabman.voodoo.driver.PS2Keyboard (1.9.2) 0AD6AD57-1F08-39DF-A616-39715E69C536 <60 56 16 8 7 6 5 3 1>
   79    0 0xffffff7f827fc000 0xc000     0xc000     org.rehabman.voodoo.driver.PS2Trackpad (1.9.2) 172C5C14-5D31-3BE0-A947-59A4F3938B90 <60 56 16 8 7 6 5 3 1>
   80    0 0xffffff7f8280a000 0x4000     0x4000     org.rehabman.voodoo.driver.PS2Mouse (1.9.2) 543C2723-E8F2-32CC-947E-F8A3B33E0E14 <60 56 6 5 3>
```

**Comment by kirainmoe** [comment]
有对 DSDT 做什么改动吗，理论上在你最开始提到触摸板能用但是不能设置手势的时候，VoodooI2CHID.kext 已经加载了，但现在不加载我也不知道为什么了。

**Comment by NealZp** [comment]
miniDP应该也是直连独显的，显示不了。NVIDIA控制面板也是显示独显输出三个接口

**Comment by zxj5470** [comment]
然后我现在把VoodooI2CHID.text丢到/Library/Extension 并且chown成root以后……现在开机进度条卡在 100% 了

**Comment by kirainmoe** [comment]
> miniDP应该也是直连独显的，显示不了。NVIDIA控制面板也是显示独显输出三个接口

是这样吗，我没有试过外接，我在 Hackintool 里看到 UHD630 有一个 LVDS 和两个 DP，我以为那两个 DP 就是直连 UHD630 的。

**Comment by kirainmoe** [comment]
> 然后我现在把VoodooI2CHID.text丢到/Library/Extension 并且chown成root以后……现在开机进度条卡在 100% 了

Clover 开 -v 看卡哪儿了

**Comment by zxj5470** [comment]
> > 然后我现在把VoodooI2CHID.text丢到/Library/Extension 并且chown成root以后……现在开机进度条卡在 100% 了
> 
> Clover 开 -v 看卡哪儿了

……我重启了一遍然后又没事了……玄学啊

**Comment by kirainmoe** [comment]
不知道为什么，我装在SSD用APFS的时候，10.14下有概率会卡条。

所以触摸板能用了吗..

**Comment by zxj5470** [comment]
回到之前的水平……设置点开找不到触摸板 但是勉强能用，左键必须按下，右键无效，只有一个全部上拉的手势。

就差电源驱动了……

**Comment by kirainmoe** [comment]
如果你之前用 DSDT 驱动电池，那现在用 SSDT hotpatch 试试，反之就提取 DSDT 用 dsdt-patch.txt 里的内容打补丁。确定没有应用过 Voodooi2c 源里的补丁吗。

**Comment by zxj5470** [comment]
我个硬件小白当然是啥都没动啦……

又到了喜闻乐见的全部替换~希望能成功吧

**Comment by zxj5470** [comment]
喜闻乐见……现在强行替换电池驱动OK，以太网驱动坏了……看来其实也不是那个 IntelMausiEthernet.kext 的问题……我再看看别的……

**Comment by kirainmoe** [comment]
看看 RTL 那个驱动加载了没有，没有的话就装到 LE去试试，如果还不行再说，我再看看我是不是又少上传了什么..

**Comment by kirainmoe** [comment]
感觉好像是 Github 上的 kext 和我本地正常工作的 kext 文件有出入的原因，不晓得出了什么问题，我把 Github 上整个下载下来到我本地替换 EFI 也是以太网不能用的……我重新传了以太网相关的驱动，这次再试试能不能用，造成不便十分抱歉

**Comment by zxj5470** [comment]
我把8111的丢进去了发现没用…我按照昨天晚上的截图一个个去看发现似乎没用…

哦对现在有时候Alt是🌸有时候Win键是🌸

**Comment by kirainmoe** [comment]
AppleIGB AppleIntelE1000 IntelMausiEthernet RealtekRT8111 全都丢进去试试，记得把安装到当前系统 L/E 的那些删掉，重建缓存

**Comment by zxj5470** [comment]
OK. 终于解决了~ 然后现在蓝牙似乎坏了23333（不过我用不着蓝牙，无所谓了）

**Comment by kirainmoe** [comment]
蓝牙需要热启动，先进 Windows 后重启进 macOS 才能部分驱动，不然 mac 地址会是一串 0. 也可以在 mac 下装一个虚拟机，把蓝牙设备挂载进去再弹出来也能修复。

那么触摸板什么的都解决了么，解决的话这个 issue 就可以关了~
