### ISSUE TITLE
同系列1050ti已经装上了，但是无法外接拓展屏？请问有什么解决方案吗？hdmi

### ISSUE THREAD

**Issue by awagege** [kirainmoe/hasee-z7-kp7gz-macos#7]

**Comment by kirainmoe** [comment]
目前无解，请看 readme：

> HDMI（该模具 HDMI 直接由独显输出, 独显无法驱动，所以 HDMI 也无法使用）

你可以尝试：

1.安装10.13.6，虽然显卡不能完全驱动但可以识别，我不清楚hdmi外接行不行。
2.买个 typec转dp或hdmi，虽然我也不知道行不行。
