### ISSUE TITLE
电池怎么样才算驱动呢

### ISSUE THREAD

**Issue by glitterlip** [kirainmoe/hasee-z7-kp7gz-macos#8]
机型是 z7kp7gc
现在电池充电,电量显示百分比斗正常,
但是打开触控板还是一直正在搜索.双指上下滑动好使,别的就不行了
试过用 kext utility装到 sle 还是不行

**Comment by kirainmoe** [comment]
1. 充电，显示百分比正常，系统信息的电池部分出现序列号厂商和容量信息，证明电池已驱动。
2. 这里是给 Z7-KP7GZ 系列型号用的 EFI，Z7-KP7GC 不属于该系列，因此我不知道你的 Z7-KP7GC 用的是不是 I2C HID 的触摸板。
3. 如果 KP7GC 用的是 I2C HID 的触摸板，那么使用 `sudo kextstat` 检查 VoodooI2C.kext, VoodooI2CHID.kext, VoodooI2CService.kext, VoodooGPIO.kext 是否加载。
4. 如果 KP7GC 用的是 I2C 触摸板但不是 HID 而是 Elan/synaptics 的触摸板，请自行到 VoodooI2C 的仓库页面下载适合的驱动替换掉 VoodooI2CHID.kext.
5. 请确保你没有安装 ApplePS2SmartTouchpad.kext.
6. 如果 KP7GC 用的不是 I2C 的触摸板，那么请下载 ApplePS2SmartTouchpad.kext 并删除 VoodooI2C 相关驱动和 VoodooPS2Controller.kext
7. 请先备份好 EFI 文件后执行以上操作，防止无法进入系统。
8. 如果以上步骤无法解决你的问题，请参照提问须知部分上传 Clover 文件夹，IORegistry输出等。或者，远景论坛有 KP7GC 的成功机型，请下载他们的 EFI 触摸板相关驱动替换。

**Comment by kirainmoe** [comment]
另外，如果 VoodooI2C 的驱动都正确加载，电池也正确驱动，尝试不接电源开机后进入触摸板设置，看看是否仍然提示搜索蓝牙触控板。

**Comment by kirainmoe** [comment]
附：关于查看触摸板是否为 I2C HID 的问题，在设备管理器的人体学输入设备部分查看是否有如下字样的设备，如果有证明是 I2C HID 触摸板。

![i2c hid device](https://wx3.sinaimg.cn/large/9f1137b1ly1g1d5dj6gl2j20wr0n276l.jpg)

**Comment by glitterlip** [comment]
好的 感谢指导
