### ISSUE TITLE
tips：亮度调节及HOME键可使用 Karabiner-Elements 修改按键

### ISSUE THREAD

**Issue by zxj5470** [kirainmoe/hasee-z7-kp7gz-macos#9]
偶然间发现按F1和按pause键居然能触发亮度……于是……
![image](https://user-images.githubusercontent.com/20026798/55278149-92a96500-5343-11e9-8be8-0582e812de3b.png)

这样就完美贴合键盘上的 F11 和 F12 了~

macOS本身的 F11 等同于四指摊开显示桌面个人认为这个功能没啥用23333

实际效果图
![image](https://user-images.githubusercontent.com/20026798/55278194-0ba8bc80-5344-11e9-94cf-34387de15ba3.png)

**Comment by kirainmoe** [comment]
这个软件我知道的，但是跟配置文件没啥关系，用户自行选用就好了，我个人更喜欢外接键盘后就能设置显示器亮度调节是F11和F12.

**Comment by zxj5470** [comment]
好吧……
另外由于这电脑的键盘没有主动的 HOME 键，键盘的驱动在 macos下小键盘又那么不尽如人意，所以我还把
PAUSE BREAK键改为了 HOME，现在就很开心了。。。

**Comment by kirainmoe** [comment]
Command+方向键左=Home，End同理。
